#!/bin/bash
echo "### Updating database host url."
DB_NAME=$APPLICATION_NAME
DB_HOST="$(aws rds describe-db-instances --db-instance-identifier $DB_NAME --query 'DBInstances[0].Endpoint.Address' --output text --region us-east-1)"
DB_PORT="$(aws rds describe-db-instances --db-instance-identifier $DB_NAME --query 'DBInstances[0].Endpoint.Port' --output text --region us-east-1)"

echo "DB_NAME: $DB_NAME"
echo "DB_HOST: $DB_HOST"
echo "DB_PORT: $DB_PORT"

unzip -f /usr/share/tomcat7/webapps/ROOT.war WEB-INF/classes/applicationContext-resources.xml

temp=$(mktemp)
cp WEB-INF/classes/applicationContext-resources.xml $temp

sed s/REPLACE_DBNAME/$DB_NAME/g $temp > $temp.new && mv $temp.new $temp
sed s/REPLACE_DBHOST/$DB_HOST/g $temp > $temp.new && mv $temp.new $temp

cp -f $temp WEB-INF/classes/applicationContext-resources.xml
zip /usr/share/tomcat7/webapps/ROOT.war WEB-INF/classes/applicationContext-resources.xml

rm -f WEB-INF/classes/applicationContext-resources.xml
rm -f $temp
